
const { createStrapi } = require('@strapi/strapi');

async function createToken() {
    try {
        console.log('Loading Strapi...');
        const strapi = createStrapi({ distDir: './dist' });
        await strapi.load();
        console.log('Strapi loaded.');

        const tokenService = strapi.service('admin::api-token');

        if (!tokenService) {
            throw new Error('API Token service not found');
        }

        const tokenName = 'NextJsFrontend';

        // List existing tokens to check for duplicates
        const tokens = await tokenService.list();
        const existing = tokens.find(t => t.name === tokenName);

        if (existing) {
            console.log(`Token '${tokenName}' already exists. Revoking...`);
            await tokenService.revoke(existing.id);
        }

        console.log(`Creating new token '${tokenName}'...`);
        const token = await tokenService.create({
            name: tokenName,
            type: 'full-access',
            description: 'Generated by Antigravity for Next.js Frontend',
            lifespan: null, // Unlimited
        });

        console.log('---------------------------------------------------');
        console.log('NEW_TOKEN:', token.accessKey);
        console.log('---------------------------------------------------');

        const fs = require('fs');
        fs.writeFileSync('new_token.txt', token.accessKey);
        console.log('Token saved to new_token.txt');

    } catch (error) {
        console.error('❌ Error creating token:', error);
    } finally {
        process.exit(0);
    }
}

createToken();
